In [1]:
import loader

/scratch/u1319464/miniforge3/envs/diabetes/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
(
    (train, train_y),
    (test, test_y),
    (val, val_y),
    (one_hot_encoder_X, one_hot_encoder_y),
    (train_df, test_df, _),
    (train_dataset, test_dataset, _),
    (train_loader, test_loader, _)
) = loader.encode_and_partition(
    loader.diabetic_data_raw, batch_size=64, labelled=True
)


In [7]:
import numpy as np
np.argmax(one_hot_encoder_X.feature_names_in_=='max_glu_serum')

20

In [11]:
np.sort(np.unique( [ str(i) for i in one_hot_encoder_X.categories_[20] ]))

array(['>200', '>300', 'Norm', 'nan'], dtype='<U4')

In [2]:
(loader.partition_train.patient_nbr==8222157).any()

True

In [3]:
len(loader.patient_nbr[loader.patient_nbr.isin(loader.partition_train.patient_nbr)])

81395

In [4]:
len(loader.train) / len(loader.diabetic_data_raw), len(loader.val) / len(loader.diabetic_data_raw)

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [ ]:
a = loader.train.loc[:0]
b = a.drop(columns='readmitted')

In [ ]:
loader.one_hot_encoder.transform(b)

In [ ]:
a

In [5]:
loader.one_hot_encoder_X.categories_

[array(['?', 'AfricanAmerican', 'Asian', 'Caucasian', 'Hispanic', 'Other'],
       dtype=object),
 array(['Female', 'Male', 'Unknown/Invalid'], dtype=object),
 array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
        '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object),
 array(['>200', '?', '[0-25)', '[100-125)', '[125-150)', '[150-175)',
        '[175-200)', '[25-50)', '[50-75)', '[75-100)'], dtype=object),
 array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 22, 23, 24, 25, 27, 28]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 17, 20, 22, 25]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array(['?', 'BC', 'CH', 'CM', 'CP', 'DM', 'FR', 'HM', 'MC', 'MD', 'MP',
        'OG', 'OT', 'PO', 'SI', 'SP', 'UN', 'WC'], dtype=object),
 array(['?', 'AllergyandImmunology', 'Anesthesiology',
        'Anesthesiology-Pediatric', 'Cardiology', 'Cardiology-Pe

In [ ]:
?